### ISSUE TITLE
Get rid of the navigator overview on the bottom right

### ISSUE THREAD

**Issue by brienna** [HEmile/juggl#63] opened 2021-05-21 19:08 UTC
I cannot seem to get rid of the navigator overview on the bottom right. 

![Screen Shot 2021-05-21 at 3 06 28 PM](https://user-images.githubusercontent.com/9706870/119186564-4307e500-ba46-11eb-8168-0712aaffeeec.png)

I have toggled its option off in the Juggl settings, but this doesn't remove it. 

![Screen Shot 2021-05-21 at 3 07 46 PM](https://user-images.githubusercontent.com/9706870/119186604-531fc480-ba46-11eb-9627-af1e4abd2395.png)

**Comment by HEmile** [comment] 2021-05-22 11:35
Hi, have you tried opening and closing the Juggl view? It should only hide it after you've closed and reopened that pane.

**Comment by brienna** [comment] 2021-05-23 22:22
I've tried opening and closing the pane, in addition to quitting and restarting Obsidian. 

![Screen Shot 2021-05-23 at 6 20 11 PM](https://user-images.githubusercontent.com/9706870/119278504-b00cad80-bbf3-11eb-9654-83e626a1a97e.png)

The reason why I'm hoping to hide the navigator is because sometimes it gets a distorted view, especially when viewing a local graph. I'm on Mac OS.

**Comment by HEmile** [comment] 2022-03-12 13:12
Haven't heard complaints about this for a while, and I cannot reproduce it (am on Mac OS). If this is still an issue, please reopen.

**Closed by HEmile** 2022-03-12 13:12 UTC
