### ISSUE TITLE
Add notes to workspace graph without "Automatically add nodes" option

### ISSUE THREAD

**Issue by chen003** [HEmile/juggl#100] opened 2022-01-16 20:29 UTC
Hi Emile, thanks for developing this amazing plugin. I'm wondering if it's possible to add notes to the current workspace graph without enabling the "Automatically add nodes" option. 

Let's say I want to add a note from the file explorer. With "Automatically add nodes" I can simply klick on the note and it automatically adds the note to the workspace graph. But when "Automatically add nodes" is disabled, the only option I found is to open a new graph with "Open Juggl".  Sometimes I just want to edit a note without open it in the graph. Sorry if options like this exist but I didn't find it.

**Comment by HEmile** [comment] 2022-01-17 08:37
This is a good question, and no not really. Maybe this is a good suite for the 'Nodes in graph' sidebar pane.

**Comment by HEmile** [comment] 2022-03-12 13:10
Going to close this as a duplicate of #56

**Closed by HEmile** 2022-03-12 13:10 UTC
